### PR TITLE
Make realm name configurable at deploy time

### PR DESCRIPTION
**Pull request by cristina-sirbu**
Make the realm name configurable

### CODE REVIEW

**Comment by salaboy** [comment]
@ryandawsonuk this looks good to me.. do you have any concerns about this? 
We should merge and bump the versions so people can consume these changes.

**Comment by salaboy** [comment]
@ryandawsonuk same here.. do you have any concerns about this?

**Comment by salaboy** [comment]
@igdianov @almerico can you guys review as well?

**Comment by ryandawsonuk** [comment]
The change looks fine to me

**Review by rgauss — APPROVED** [review]

**Pull request merged**
