### PR TITLE
ACTIVITI-2645 Make audit + query + rb use the postgres found in the a…

### PR DESCRIPTION
**Pull request by roxana-enasoaie**
Make audit + query + rb use the postgres found in the application namespace

### CODE REVIEW

**Comment by ryandawsonuk** [comment]
The changes look fine to me. Are there further changes coming? I ask because it will take us a while to apply the same changes to the other places where we have these charts as each of our example repositories has its own chart (just for runtime bundle these are example-runtime-bundle, ttc-rb-english-campaign and activiti-cloud-runtime-bundle-quickstart). So it would be good know that we've got all the changes in one go.

**Comment by ffazzini** [comment]
sounds great @ryandawsonuk  
As a last step we want to test the activiti cloud chart to make sure we are able to use an external postgres too. As a result of this test we won't have any postgres deployed in kubernetes. Sounds good?

**Comment by ryandawsonuk** [comment]
I was assuming that these changes were being proposed as a result of testing. I guess there's a further scenario that also needs testing?

**Comment by ffazzini** [comment]
@ryandawsonuk yes the scenario i described above, have you already tested it?

**Comment by roxana-enasoaie** [comment]
We just tested the charts on an external db and it works fine.
One example for this would be: 
```
runtime-bundle:
  enabled: true
  db:
    uri: jdbc:postgresql://*.rds.amazonaws.com/activitidb
    username: alfresco
    password: changeme
    driver: org.postgresql.Driver
    platform: org.hibernate.dialect.PostgreSQLDialect
    generateDdl: true
    ddlAuto: update
```

**Pull request merged**
